Traceback (most recent call last):
  File "/home/pedro/PINN/jaxpi/examples/geomI/main.py", line 39, in <module>
    app.run(main)
  File "/usr/local/lib/python3.11/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.11/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/pedro/PINN/jaxpi/examples/geomI/main.py", line 31, in main
    train.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "/home/pedro/PINN/jaxpi/examples/geomI/train.py", line 68, in train_and_evaluate
    coords_fem = coords_fem / L_star
                 ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'coords_fem' where it is not associated with a value